interval: 1.0

probes:

  # 本地
  - label: Local PING
    type: icmp
    host: 127.0.0.1

  # 局域网
  - label: Gateway PING
    type: icmp
    host: 192.168.1.1

  # 国内网站
  - label: QQ PING
    type: icmp
    host: qq.com

  # 国内 DNS
  - label: Ali DNS
    type: dns
    domain: qq.com
    dns: 223.5.5.5

  # 国际网站
  - label: GitHub TCP
    type: tcp
    host: github.com
    port: 443

  # 国际网站
  - label: Google HTTP 
    type: http     # TCP 不走代理, 一般都不通, 推荐用 http 测试
    url: https://www.google.com/generate_204